<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Tommy Dinh" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<pre class="r"><code>library(AER)
aff &lt;- read.csv(&quot;Affairs.csv&quot;)</code></pre>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<pre class="r"><code>head(aff)</code></pre>
<pre><code>## X affairs gender age yearsmarried children religiousness
education occupation rating
## 1 4 0 male 37 10.00 no 3 18 7 4
## 2 5 0 female 27 4.00 no 4 14 6 4
## 3 11 0 female 32 15.00 yes 1 12 1 4
## 4 16 0 male 57 15.00 yes 5 18 6 5
## 5 23 0 male 22 0.75 no 2 17 6 3
## 6 29 0 female 32 1.50 no 2 17 5 5</code></pre>
<p><em>I chose the Affairs dataset. I was going through the available packages in R and this one caught my eye. It is a little outdated (from 1969). There are 601 observations with 9 variables. The main ones I want to focus on are affairs: which indicate the number of marital affairs the individual reported in the past year, their age, their rating on how happy they are in their marriage.</em></p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss some of the MANOVA assumptions and whether or not they are likely to have been met here (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>library(rstatix)
man &lt;- manova(cbind(age,rating)~affairs, data=aff)
man</code></pre>
<pre><code>## Call:
##    manova(cbind(age, rating) ~ affairs, data = aff)
## 
## Terms:
##                  affairs Residuals
## age               469.55  51299.11
## rating             57.05    673.15
## Deg. of Freedom        1       599
## 
## Residual standard errors: 9.254256 1.060093
## Estimated effects may be unbalanced</code></pre>
<pre class="r"><code>summary(man) </code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## affairs 1 0.079761 25.916 2 598 1.608e-11 ***
## Residuals 599
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man)</code></pre>
<pre><code>## Response age :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## affairs 1 470 469.55 5.4827 0.01953 *
## Residuals 599 51299 85.64
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response rating :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## affairs 1 57.05 57.049 50.764 3.002e-12 ***
## Residuals 599 673.15 1.124
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(aff$age, aff$affairs, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  aff$age and aff$affairs 
## 
##    0     1     2     3     7    
## 1  0.242 -     -     -     -    
## 2  0.282 0.111 -     -     -    
## 3  0.873 0.391 0.493 -     -    
## 7  0.164 0.061 0.885 0.498 -    
## 12 0.055 0.024 0.843 0.308 0.657
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(aff$rating, aff$affairs, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  aff$rating and aff$affairs 
## 
##    0       1       2       3       7      
## 1  0.51476 -       -       -       -      
## 2  0.05367 0.22381 -       -       -      
## 3  0.00039 0.01232 0.28491 -       -      
## 7  0.00032 0.04306 0.71245 0.36370 -      
## 12 1.7e-09 0.00011 0.05698 0.47870 0.04465
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>group &lt;- aff$affairs 
DVs &lt;- aff %&gt;% select(age, rating)
sapply(split(DVs,group), mshapiro_test)</code></pre>
<pre><code>## 0 1 2 3 7 12
## statistic 0.9331716 0.9124625 0.8670838 0.9593522
0.9225058 0.9390568
## p.value 2.498192e-13 0.00995227 0.01975336 0.5596847
0.007298631 0.0390473</code></pre>
<p><em>I ran 5 tests: 2 Anovas, 2 t-tests, and a Manova. The first performed was a Manova which yielded a Pillai value of 0.079761, an F of approximately 25.916 and a significant p value of 1.608e-11.Then, I ran two univariate Anova tests on age and rating which also yielded significant results. The age and rating yielded F values of 5.4827 and 50.764 and P values of 0.01953 and 3.002e-12, respectively. Finally, I conducted pairwise t-tests and as seen above there was a significant p-value in all except for 3.</em></p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>library(vegan)
library(tidyverse)
aff %&gt;% group_by(gender) %&gt;% summarise(means = mean(affairs)) %&gt;% summarise(mean_diff=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1    0.0775</code></pre>
<pre class="r"><code>rand_dist &lt;- vector()
for (i in 1:5000) {
  new &lt;- data.frame(affairs = sample(aff$affairs), gender = aff$gender)
  rand_dist[i] &lt;- mean(new[new$gender ==&quot;male&quot;, ]$aff) - mean(new[new$gender == &quot;female&quot;, ]$aff)
}

hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = c(-.07745588, .07745588),col=&quot;red&quot;) </code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt; .07745588    | rand_dist &lt; -.07745588   )</code></pre>
<pre><code>## [1] 0.7666</code></pre>
<p><em>The mean difference of our randomization tests was.07745588. We failed to reject the null hypothesis because our p value was was too large (0.7564). </em></p>
<ul>
<li><p><strong>3. (40 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code> using geom_smooth(method=“lm”). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the <code>interactions</code> package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (10)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (5)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (10)</li>
</ul></li>
</ul>
<pre class="r"><code>aff$ym &lt;- aff$yearsmarried - mean(aff$yearsmarried)
aff$rate &lt;- aff$rating - mean(aff$rating)
fit1 &lt;- lm(rate ~ affairs*ym, data=aff)

summary(fit1)</code></pre>
<pre><code>##
## Call:
## lm(formula = rate ~ affairs * ym, data = aff)
##
## Residuals:
## Min 1Q Median 3Q Max
## -3.2064 -0.7439 0.2064 0.7936 2.2561
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 0.117853 0.046499 2.535 0.0115 *
## affairs -0.077510 0.014611 -5.305 1.59e-07 ***
## ym -0.037534 0.008290 -4.527 7.21e-06 ***
## affairs:ym -0.001460 0.002623 -0.557 0.5779
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 1.04 on 597 degrees of freedom
## Multiple R-squared: 0.1163, Adjusted R-squared: 0.1119
## F-statistic: 26.2 on 3 and 597 DF, p-value: 6.225e-16</code></pre>
<pre class="r"><code>coef(fit1)</code></pre>
<pre><code>##  (Intercept)      affairs           ym   affairs:ym 
##  0.117853291 -0.077509837 -0.037533663 -0.001460325</code></pre>
<pre class="r"><code>aff %&gt;% ggplot(aes(ym, rate)) + geom_point() + geom_smooth(method = &#39;lm&#39;, se=F, fullrange=T)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>cor(aff$rate, aff$ym)</code></pre>
<pre><code>## [1] -0.2431188</code></pre>
<pre class="r"><code>res &lt;- fit1$residuals
fitted &lt;- fit1$fitted.values

#Homoskedasticity
ggplot() + geom_point(aes(fitted, res)) + geom_hline(yintercept = 0, color= &#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot() + geom_histogram(aes(res))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot() + geom_qq(aes(sample = res))+geom_qq()</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>coeftest(fit1)</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 0.1178533 0.0464988 2.5345 0.01151 *
## affairs -0.0775098 0.0146105 -5.3051 1.589e-07 ***
## ym -0.0375337 0.0082905 -4.5273 7.214e-06 ***
## affairs:ym -0.0014603 0.0026226 -0.5568 0.57785
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>coeftest(fit1, vcov=vcovHC(fit1))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 0.1178533 0.0456339 2.5826 0.01004 *
## affairs -0.0775098 0.0164978 -4.6982 3.261e-06 ***
## ym -0.0375337 0.0082064 -4.5737 5.829e-06 ***
## affairs:ym -0.0014603 0.0030719 -0.4754 0.63469
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>fit2 &lt;- lm(yearsmarried ~ rating, data = aff)
SSR &lt;- sum((fit2$fitted.values-mean(aff$rating)))
SST &lt;- sum((aff$rating-mean(aff$rating))^2)
SSR/SST</code></pre>
<pre><code>## [1] 3.494638</code></pre>
<p><em>The coefficient was negative which means that the more years that an individual is married the lower their reported mean rating of happiness is in their relationship, which is very saddening. The model doesn’t show any violation of homoskedacity as there seems to be an even distribution throughout and little to no clustering. There is good linearity in my model as it there are scattered trends of decrease throughout. Normality assumption was also met from the graphs. According to the coeftests there were significant for the number of affairs and years married model.</em></p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {
boot_dat&lt;-boot_dat&lt;-aff[sample(nrow(aff),replace=TRUE),]
fit&lt;-lm(aff$rate ~ aff$affairs*aff$ym, data=boot_dat)
coef(fit)
})</code></pre>
<p><em>After running a bootstrapped version of the same regression model, the outputs did not change.</em></p>
<ul>
<li><p><strong>5. (30 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (5)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (5)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code>library(plotROC)

binary &lt;- aff%&gt;%mutate(y=ifelse(gender==&quot;male&quot;,1,0))
head(binary)</code></pre>
<pre><code>## X affairs gender age yearsmarried children religiousness
education occupation rating ym
## 1 4 0 male 37 10.00 no 3 18 7 4 1.822304
## 2 5 0 female 27 4.00 no 4 14 6 4 -4.177696
## 3 11 0 female 32 15.00 yes 1 12 1 4 6.822304
## 4 16 0 male 57 15.00 yes 5 18 6 5 6.822304
## 5 23 0 male 22 0.75 no 2 17 6 3 -7.427696
## 6 29 0 female 32 1.50 no 2 17 5 5 -6.677696
## rate y
## 1 0.06821963 1
## 2 0.06821963 0
## 3 0.06821963 0
## 4 1.06821963 1
## 5 -0.93178037 1
## 6 1.06821963 0</code></pre>
<pre class="r"><code>fit2 &lt;- glm(y~affairs, data = binary, family=binomial(link=&quot;logit&quot;))
coeftest(fit2) %&gt;% addmargins()</code></pre>
<pre><code>## Estimate Std. Error z value Pr(&gt;|z|) Sum
## (Intercept) -0.106961597 0.08930996 -1.1976446 0.2310554
-0.9842408
## affairs 0.007122698 0.02475995 0.2876701 0.7735993
1.0931520
## Sum -0.099838899 0.11406992 -0.9099745 1.0046547
0.1089112</code></pre>
<pre class="r"><code>exp(coef(fit2))</code></pre>
<pre><code>## (Intercept)     affairs 
##   0.8985602   1.0071481</code></pre>
<pre class="r"><code>logis &lt;- function(x){exp(x)/(1+exp(x))}

table(truth=binary$affairs&gt;0, prediction=binary$gender) %&gt;% addmargins()</code></pre>
<pre><code>##        prediction
## truth   female male Sum
##   FALSE    243  208 451
##   TRUE      72   78 150
##   Sum      315  286 601</code></pre>
<pre class="r"><code>acc &lt;- (72+78)/601
acc</code></pre>
<pre><code>## [1] 0.249584</code></pre>
<pre class="r"><code>TPR &lt;- (78/286)
TPR</code></pre>
<pre><code>## [1] 0.2727273</code></pre>
<pre class="r"><code>TNR &lt;- 72/150
TNR</code></pre>
<pre><code>## [1] 0.48</code></pre>
<pre class="r"><code>PPV &lt;- 78/150
PPV</code></pre>
<pre><code>## [1] 0.52</code></pre>
<pre class="r"><code>aff$logit&lt;-predict(fit2) 
aff$numAff&lt;-as.factor(aff$affairs)
ggplot(aff, aes(logit, fill=gender)) + geom_density(alpha=.5)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)

ROCplot &lt;- ggplot(binary) +geom_roc(aes(d=y, m=aff$affair), n.cuts = 0) 
ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.5192086</code></pre>
<p><em>The model yielded a poor accuracy of .250, sensitivity of .273, specificity of .48, and auc value of 0.519.</em></p>
<ul>
<li><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</li>
</ul>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]
if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
ord&lt;-order(probs, decreasing=TRUE)
probs &lt;- probs[ord]; truth &lt;- truth[ord]
TPR=cumsum(truth)/max(1,sum(truth))
FPR=cumsum(!truth)/max(1,sum(!truth))
dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
n &lt;- length(TPR)
auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
data.frame(acc,sens,spec,ppv,auc)
}</code></pre>
<pre><code>- Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)
- Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)
- Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., `lambda.1se`). Discuss which variables are retained. (5)
- Perform 10-fold CV using only the variables lasso selected: compare model&#39;s out-of-sample AUC to that of your logistic regressions above (5)</code></pre>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>.
Run <code>install.packages("fivethirtyeight"),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
